-- Manually creating AdministrativeStaff and PersonalTrainer because from my experience, employees get their emails assigned to them, so I am defining them in the DML itself to simulate that. 
INSERT INTO PersonalTrainer (fName, lName, email, password, phoneNumber)
VALUES ('Arnold', 'Schwarznegger', 'ArnoldSchwarznegger@PallavGym.com', 'arnold123', '(123) 123-1234'),
       ('Christian', 'Bale', 'ChrisBale@PallavGym.com', 'chris123', '(123) 456-7690'),
       ('Cristiano', 'Ronaldo', 'CristianoRonaldo@PallavGym.com', 'Cr!st1@no', '(613) 123-4567'),
       ('Lionel', 'Messi', 'LionelMessi@PallavGym.com', 'LeoMessi!1', '(416) 111-1111');

INSERT INTO AdministrativeStaff (fName, lName, email, password, phoneNumber)
VALUES ('Keanu', 'Reeves', 'KeanuReeves@PallavGym.com', 'JohnWick1', '(647) 123-4567'),
       ('Alicia', 'Keys', 'AKeys@PallavGym.com', 'Alicia123', '(437) 437-4370'),
       ('Jackie', 'Chan', 'JackieChan@PallavGym.com', 'J@ck1eCh@n', '(343) 333-3333');

-- Manually entering the gym's equipment into the system. This includes multiple bench presses, squat machines, cable machines, adjustable benches, cable machines, etc
INSERT INTO Equipment (equipmentName, underMaintenance)
VALUES ('Barbell Bench Press Machine', FALSE),
       ('Barbell Bench Press Machine', TRUE),
       ('Barbell Bench Press Machine', FALSE),
       ('Barbell Bench Press Machine', TRUE),
       ('Squat Rack', TRUE),
       ('Squat Rack', FALSE),
       ('Squat Rack', FALSE),
       ('Squat Rack', FALSE),
       ('Squat Rack', FALSE),
       ('Cable Machine', FALSE),
       ('Cable Machine', FALSE),
       ('Cable Machine', FALSE),
       ('Adjustable Bench', FALSE),
       ('Adjustable Bench', FALSE),
       ('Adjustable Bench', FALSE),
       ('Adjustable Bench', FALSE),
       ('Adjustable Bench', FALSE),
       ('Leg Press Machine', FALSE),
       ('Lying Leg Curl Machine', FALSE),
       ('Leg Curl Machine', FALSE),
       ('Standing Calf Raise Machine', FALSE),
       ('Seated Calf Raise Machine', FALSE),
       ('Hip Abductor / Adductor Machine', FALSE),
       ('Dumbbell Set (5 to 100 lbs)', FALSE),
       ('Dumbbell Set (5 to 100 lbs)', FALSE),
       ('Treadmill', TRUE),
       ('Treadmill', TRUE),
       ('Treadmill', FALSE),
       ('Treadmill', FALSE),
       ('Treadmill', FALSE),
       ('Stationary Bike', FALSE),
       ('Stationary Bike', FALSE),
       ('Stationary Bike', FALSE),
       ('Stationary Bike', TRUE),
       ('Rowing Machine', FALSE),
       ('Assisted Pull Up and Dip Machine', FALSE),
       ('Smith Machine', FALSE),
       ('Smith Machine', FALSE),
       ('Rear Delt / Pec Fly Machine', FALSE),
       ('Rear Delt / Pec Fly Machine', FALSE),
       ('Tricep Extension Machine', FALSE),
       ('Lat Pulldown Machine', FALSE),
       ('Lat Pulldown Machine', FALSE),
       ('Seated Row Machine', FALSE),
       ('Seated Row Machine', TRUE),
       ('Bicep Curl Machine', FALSE);

-- For all equipment that is currently under maintenance, adding an entry in the EquipmentMaintenance table with a NULL completion date (as the equipment is still undergoing maintenance and is not completed) (this is the default value)
INSERT INTO EquipmentMaintenance (equipmentId)
SELECT equipmentId FROM Equipment WHERE underMaintenance = TRUE;

-- Adding some maintenance info for some of the equipment. Arbitrarily choosing some equipment ID to maintain at some dates that I arbitrarily chose
WITH equipmentIdOffset AS (
  SELECT MIN(equipmentId) - 1 AS equipmentIdOffset FROM Equipment
)
INSERT INTO EquipmentMaintenance (equipmentId, maintenanceCompletionDate)
VALUES ((SELECT equipmentIdOffset FROM equipmentIdOffset) + 1, '2023-01-30 18:00:00'),
       ((SELECT equipmentIdOffset FROM equipmentIdOffset) + 5, '2023-01-30 18:00:00'),
       ((SELECT equipmentIdOffset FROM equipmentIdOffset) + 12, '2023-01-30 18:00:00'),
       ((SELECT equipmentIdOffset FROM equipmentIdOffset) + 19, '2023-01-30 18:00:00'),
       ((SELECT equipmentIdOffset FROM equipmentIdOffset) + 28, '2023-01-30 18:00:00'),
       ((SELECT equipmentIdOffset FROM equipmentIdOffset) + 15, '2023-05-23 12:00:00'),
       ((SELECT equipmentIdOffset FROM equipmentIdOffset) + 17, '2023-05-23 12:00:00'),
       ((SELECT equipmentIdOffset FROM equipmentIdOffset) + 33, '2023-05-23 12:00:00'),
       ((SELECT equipmentIdOffset FROM equipmentIdOffset) + 40, '2023-05-23 12:00:00'),
       ((SELECT equipmentIdOffset FROM equipmentIdOffset) + 44, '2023-12-11 20:00:00'),
       ((SELECT equipmentIdOffset FROM equipmentIdOffset) + 10, '2023-12-11 20:00:00'),
       ((SELECT equipmentIdOffset FROM equipmentIdOffset) + 17, '2023-12-11 20:00:00'),
       ((SELECT equipmentIdOffset FROM equipmentIdOffset) + 19, '2023-12-11 20:00:00');

INSERT INTO Room (roomNumber, roomName)
VALUES (100, 'Yoga Room'),
       (101, 'Boxing Room'),
       (102, 'Studio 1'),
       (103, 'Studio 2');

INSERT INTO Exercise (exerciseName, exerciseDescription) 
VALUES ('Bench Press (Barbell)', 'Muscles targeted: Chest, Shoulders, Triceps'),
       ('Skullcrushers (EZ bar)', 'Muscles targeted: Triceps'),
       ('Skullcrushers (Dumbbell)', 'Muscles targeted: Triceps'),
       ('Incline Bench Press (Barbell)', 'Muscles targeted: Upper Chest, Shoulders, Triceps'),
       ('Bench Press (Dumbbell)', 'Muscles targeted: Chest, Shoulders, Triceps'),
       ('Incline Bench Press (Dumbbell)', 'Muscles targeted: Upper Chest, Shoulders, Triceps'),
       ('Shoulder Press (Dumbbell)', 'Muscles targeted: Shoulders, Upper Back'),
       ('Chest Fly (Cable)', 'Muscles targeted: Pectorals, Deltoids, Triceps, Core'),
       ('Chest Fly (Machine)', 'Muscles targeted: Pectorals, Deltoids'),
       ('Rear Deltoid (Machine)', 'Muscles targeted: Rear Deltoids'),
       ('Tricep Extensions (Machine)', 'Muscles targeted: Triceps'),
       ('Leaning Lateral Raises (Dumbbell)', 'Muscles targeted: Anterior, Lateral, and Posterior Deltoids'),
       ('Lateral Raises (Dumbbell)', 'Muscles targeted: Lateral and Front Deltoids'),
       ('Chest Dips', 'Muscles targeted: Chest, Triceps, Shoulders'),
       ('Pull Ups', 'Muscles targeted: Lats, Back, Biceps, Shoulders'),
       ('Chin Ups', 'Muscles targeted: Biceps, Posterior Deltoids, Back, Shoulder'),
       ('Muscle Ups', 'Muscles targeted: Core, Back, Shoulders, Biceps, Triceps'),
       ('Squat (Barbell)', 'Muscles targeted: Quadriceps, Hamstrings, Glutes'),
       ('Hack Squat (Machine)', 'Muscles targeted: Calves, Quadriceps, Hamstrings, Glutes'),
       ('Leg Press', 'Muscles targeted: Quadriceps, Hamstrings, Glutes'),
       ('Leg Extensions (Machine)', 'Muscles targeted: Quadriceps'),
       ('Leg Curl (Machine)', 'Muscles targeted: Hamstrings, Calves'),
       ('Lying Leg Curl (Machine)', 'Muscles targeted: Hamstrings, Calves'),
       ('Standing Calf Raise (Machine)', 'Muscles targeted: Calves'),
       ('Seated Calf Raise (Machine)', 'Muscles targeted: Calves'),
       ('Hip Abductor (Machine)', 'Muscles targeted: Hip Abductors'),
       ('Hip Adductor (Machine)', 'Muscles targeted: Hip Adductors'),
       ('Hip Thrusts (Machine)', 'Muscles targeted: Glutes'),
       ('Deadlift', 'Muscles targeted: Lower Back, Hamstrings, Glutes, Core'),
       ('Romanian Deadlift', 'Muscles targeted: Lower Back, Hamstrings, Glutes'),
       ('Lat Pulldown (Cable)', 'Muscles targeted: Back, Biceps, Lats'),
       ('Seated Row (Cable)', 'Muscles targeted: Upper Back, Lats, Rear Deltoids, Biceps'),
       ('Seated Row (Machine)', 'Muscles targeted: Upper Back, Lats, Rear Deltoids, Biceps'),
       ('Bent Over One Arm Row (Dumbbell)', 'Muscles targeted: Lats, Trapezius, Rear Deltoids'),
       ('Bent Over Row (Barbell)', 'Muscles targeted: Upper Back, Lats, Rear Deltoids, Biceps'),
       ('T-Bar Row (Machine)', 'Muscles targeted: Upper Back, Lats, Rear Deltoids, Biceps'),
       ('Seated One Arm Row (Cable)', 'Muscles targeted: Lats, Rhomboids'),
       ('Hammer Curl (Dumbbell)', 'Muscles targeted: Biceps, Brachialis'),
       ('Bicep Curl (Dumbbell)', 'Muscles targeted: Biceps'),
       ('Bicep Curl (Barbell)', 'Muscles targeted: Biceps'),
       ('Bicep Curl (Machine)', 'Muscles targeted: Biceps'),
       ('Bicep Curl (EZ Bar)', 'Muscles targeted: Biceps'),
       ('Bicep Curl (Concentration)', 'Muscles targeted: Biceps'),
       ('Inner Forearm Curl (Barbell)', 'Muscles targeted: Inner Forearms'),
       ('Inner Forearm Curl (Dumbbell)', 'Muscles targeted: Inner Forearms'),
       ('Outer Forearm Curl (Barbell)', 'Muscles targeted: Outer Forearms'),
       ('Outer Forearm Curl (Dumbbell)', 'Muscles targeted: Outer Forearms'),
       ('Shoulder Shrug (Barbell)', 'Muscles targeted: Trapezius'),
       ('Shoulder Shrug (Dumbbell)', 'Muscles targeted: Trapezius'),
       ('Pushups', 'Muscles targeted: Chest, Shoulders, Triceps, Core'),
       ('Plank', 'Muscles targeted: Core, Abdominals, Obliques, Shoulders, Back'),
       ('Seated Shoulder Press (Barbell)', 'Muscles targeted: Shoulders, Upper Back'),
       ('Military Press (Barbell)', 'Muscles targeted: Shoulders, Upper Back'),
       ('Seated Shoulder Press (Machine)', 'Muscles targeted: Shoulders, Upper Back'),
       ('Front Raise (Dumbbell)', 'Muscles targeted: Front Deltoids'),
       ('Front Raise (Barbell)', 'Muscles targeted: Front Deltoids'),
       ('Face Pull (Cable)', 'Muscles targeted: Rear Deltoids, Upper Back, Rear Shoulders'),
       ('Chest Press (Machine)', 'Muscles targeted: Chest, Shoulders, Triceps'),
       ('Incline Chest Press (Machine)', 'Muscles targeted: Upper Chest, Shoulders, Triceps'),
       ('Chest Fly (Dumbbell)', 'Muscles targeted: Pectorals, Deltoids'),
       ('Lat Pulldown (Machine)', 'Muscles targeted: Back, Biceps, Lats'),
       ('Close Grip Lat Pulldown (Machine)', 'Muscles targeted: Back, Biceps, Forearms'),
       ('Close Grip Lat Pulldown (Cable)', 'Muscles targeted: Back, Biceps, Forearms'),
       ('Reverse Fly (Dumbbell)', 'Muscles targeted: Rear Deltoids, Upper Back'),
       ('Reverse Fly (Machine)', 'Muscles targeted: Rear Deltoids, Upper Back'),
       ('Bent Over Lateral Raise (Dumbbell)', 'Muscles targeted: Rear Deltoids, Lower Back'),
       ('Single Arm Dumbbell Shoulder Press', 'Muscles targeted: Shoulders, Upper Back'),
       ('Dumbbell Pullover', 'Muscles targeted: Chest, Back, Triceps, Shoulders'),
       ('Barbell Pullover', 'Muscles targeted: Chest, Back, Triceps, Shoulders'),
       ('Straight Arm Pulldown (Cable)', 'Muscles targeted: Lats, Triceps'),
       ('Cable Crunch (Cable)', 'Muscles targeted: Abdominals, Obliques'),
       ('Leg Raise', 'Muscles targeted: Lower Abdominals'),
       ('Hanging Leg Raise', 'Muscles targeted: Lower Abdominals'),
       ('Side Plank', 'Muscles targeted: Obliques, Core'),
       ('Russian Twist', 'Muscles targeted: Obliques, Core'),
       ('Medicine Ball Twist', 'Muscles targeted: Obliques, Core'),
       ('Abdominal Crunch (Machine)', 'Muscles targeted: Abdominals, Obliques'),
       ('Abdominal Crunch', 'Muscles targeted: Abdominals, Obliques');